travis:
  secure:
    BINSTAR_TOKEN: R9S5ipoL/9OoVnwmYll/uoWU7nkQSm+XfnoIR3xFtNDm49Ocf8twCarAX6Dl1REYbwfjID455fTdBroV1nXgkJJp+kFg/AxufwOUWfIV46qS/hClN48Th1cmTVf2+HMrPgk0oXFo7B6NiUKQJ6M5tiadfexuH78Sf+4wLygnUAu/aS7TVmxtBSZCiRIW+xcyBtDql2UJ58apymBEAlJ7AyhgvANMDck086KchMxPtLX9IUIP2c8AICcYiFa2UxCi6C/XDmmJwajtlKHM3wgqIB3qZf2f1D6r1rmZZnKoqOceZoSR4kV1rxGZOUuY8O0AHQyQZxxItzYQjfQ9rfOeMaf4Xe+ArWPG+aN9AtICPGkGlDGwjffTm4hc1JcIukG81vh0EpS73ZquwqdcYjgem4bNY31NaXRTgOYUWnJKNWmFUbg4UB/Bv+GchcwrlsRBaOa7/VFMlKShmH8E4o68n4ZVtZ/LEbVXYYlh5vmg2zYN4d3R5dF+S9b8vm4+AbpTzkgS+NoEo8cUcmRDf9wVRUHBThEbcwp1XnvRkBTwsTeD1jQH2xYjgCQ5P47EIIJpYRmrLvAAvljaeudVrhmV7uieZt2Y8JVDTqed6XO+eEndSRBnIWDaqbE80/GPeqJB7h4u331SOeNlJg818xZxUQ7k0QOYFT18ye9lBbyt00s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
